language: java
jdk:
    - oraclejdk8
    
branches:
    except:
    only:
        - master
notifications:
    email:
        recipients:
            -
        on_success: always 
        on_failure: always 
script:
    
    - java ntou.cs.sorter.MySorter
    - java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore
     ntou.cs.sorter.MySorterTest

