language: java
jdk:
    - oraclejdk8
    - oraclejdk7
branches:
#   except:
    only:
        - master
notifications:
    email:
        recipients:
#           -
        on_success: always #always¡Bnever»Pchange
        on_failure: always #always¡Bnever»Pchange

beforeinstall:

install:

beforescript:

script:
       ntou.cs.sorter.MySorterTest

after_success:

after_failure:

before_deploy:

deploy:

after_deploy:

after_script: